name: CI
on:
  push:
    branches:
      - dev/admin-user-index
  pull_request:
    branches:
      - '**'
jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1.9'
        extensions: mbstring, intl
        coverage: none
    - name: Composer install
      run: |
        composer install --ignore-platform-reqs
    - name: Dry-run php-cs-fixer
      run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --diff-format=udiff --using-cache=no . || true
    - name: Execute php-cs-fixer
      run: |
        ./vendor/bin/php-cs-fixer fix --using-cache=no
    - name: Execute phpstan
      run: |
        ./vendor/bin/phpstan analyse
  test-suite:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.30
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: docker-database
          MYSQL_USER: docker
          MYSQL_PASSWORD: docker
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1.9'
        extensions: mbstring, intl
        coverage: none
    - name: Composer install
      run: |
        composer install --ignore-platform-reqs
    - name: Copy env
      run: cp .env.example .env
    - name: Encryption Key generate
      run: php artisan key:generate
    - name: Run Migrate
      env:
        DB_HOST: 127.0.0.1
      run: php artisan migrate
    - name: Run PHPUnit
      env:
        DB_HOST: 127.0.0.1
      run: vendor/bin/phpunit